server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:8889/orderdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
